#Handling error begins with begin rescue and end
lucky_numbers = [1, 2, 6, 7, 9]

begin

  puts lucky_numbers["me"]

rescue
  puts "TypeError"


end
